
on: push
name: Inline Python Action
jobs:
  my-job:
    name: My job
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Inline python step
      run: |
        import os 
        import json
        import urllib
        
        a = ${{ github.event.head_commit.message }}
        b = float(a)
        print(b)
      shell: python
