# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
    - 'GymOVRV1.bin'
    - 'added_file_1.txt'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  my_first_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Convert commit message title to float
        run: |
          import os 
          
          string_commit_title = ${{ github.event.head_commit.message }}
          float_commit_title = float(string_commit_title)
          print(float_commit_title)
        shell: python
        
      # change version at update.json file
      - name: Set version using commit message
        uses: jossef/action-set-json-field@v1
        with:
          file: 'update.json'
          field: 'version'
          value:  5
          
      - run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "commit by main.yml action"
          git push
      
      # Runs a single command using the runners shell
      - name: Print commit message
        run: echo "${{ github.event.head_commit.message }}"

          echo test, and deploy your project.
